name = "TestChainRulesOverload"
uuid = "cc61de7d-6035-4578-8496-421f44449a8f"
authors = ["Gaurav Arya <gauravarya272@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
